[versions]
java = "17"
kotlin = "2.2.21"

[libraries]
demo-android = { module = "com.google.android:android", version = "4.1.1.4" }
demo-androidx-browser = { module = "androidx.browser:browser", version = "1.9.0" }
demo-androidx-camera = { module = "androidx.camera:camera-view", version = "1.5.1" }
demo-androidx-fragment = { module = "androidx.fragment:fragment", version = "1.8.9" }
junit-bom = { module = "org.junit:junit-bom", version = "6.0.1" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params" }

[plugins]
android = { id = "com.android.application", version = "8.13.1" }
dokka = { id = "org.jetbrains.dokka-javadoc", version = "2.1.0" }
importClasses = { id = "io.github.gmazzo.importclasses", version = "1.3.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-samReceiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
gitVersion = { id = "io.github.gmazzo.gitversion", version = "1.5.1" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
publicationsReport = { id = "io.github.gmazzo.publications.report", version = "1.3.3" }
