[versions]
java = "17"
kotlin = "2.1.0"

[libraries]
androidx-fragment = { module = "androidx.fragment:fragment", version = "1.8.5" }
junit-bom = { module = "org.junit:junit-bom", version = "5.11.3" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params" }

[plugins]
android = { id = "com.android.application", version = "8.7.2" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-samReceiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "1.3.0" }
